
let articles= [
        {category: "world", headline: " New England on alert for robust nor'easter early week", description: " By Alyssa Smithmyer, AccuWeather Meteorologist.", url: "", imageUrl: " https://cms.accuweather.com/wp-content/uploads/2023/03/page-5-2.jpg?w=632", postedDate: "2023-03-1"},
        {category: "local", headline: " Andhra Pradesh to witness a hotter summer this 2023, warns IMD", description: " Maximum temperatures across the state have already touched 35 to 38 degree Celsius in February and are expected to rise up to 46–48 degrees Celsius, especially in the coastal region by May, says the IMD..", url: "https://timesofindia.indiatimes.com/city/visakhapatnam/brace-yourself-for-hotter-days-warns-imd-in-andhra-pradesh/articleshow/98193641.cms",imageUrl:"https://static.toiimg.com/thumb/msid-98193786,imgsize-886984,width-400,resizemode-4/98193786.jpg", postedDate: "2023-02-24"},

        {category: "india", headline: "why-climate-change-is-the-greatest-threat-to-human-progress", description: " Since 1990, Human Development Index had been on an upward trajectory. But not anymore, with successive declines seen in 2020 and 2021..", url: "", imageUrl: " https://economictimes.indiatimes.com/thumb/msid-98491302,width-100,height-75/small-biz/trade/exports/insights/why-climate-change-is-the-greatest-threat-to-human-progress.jpg", postedDate: "2023-03-8"},
        {category: "local", headline: " Climate change brings abundant groundwater to Anantapur ", description: " A farmer pumps water into her field through a borewell in Kuderu in Anantapur district. | Photo Credit: R.V.S. PRASAD.", url: " https://www.thehindu.com/news/national/andhra-pradesh/climate-change-brings-abundant-groundwater-to-anantapur-with-photo/article66508985.ece", imageUrl: " https://th-i.thgim.com/public/incoming/c8iddr/article66512302.ece/alternates/LANDSCAPE_660/4842_14_2_2023_19_41_42_2_14GROUNDWATER2.JPEG", postedDate: "2023-03-15"},
        {category: "india", headline: "Work on climate resilience agriculture for greater good of farmers: Atul Bora", description: ". Bora said that each eligible farmer of the State must get the benefit of PM- Kisan scheme. He was addressing on the second day of the two-day workshop on \"Reasons for Variations in Agriculture Productivity across the State\" organised by Department of Agriculture.", url: " https://economictimes.indiatimes.com/topic/india-climate-change", imageUrl: " https://economictimes.indiatimes.com/thumb/msid-98459429,width-100,height-75/news/india/work-on-climate-resilience-agriculture-for-greater-good-of-farmers-atul-bora.jpg", postedDate: "2023-03-08"},
        {category: "world", headline: "At least 2 dead following latest California storm", description: "The parade of storms through California continued on Friday as the state's 10th atmospheric river of the winter prompted evacuation orders for hundreds and inundated areas once wrought with drought.", url: "accuweather.com/en/severe-weather/at-least-2-dead-following-latest-california-storm/1495955", imageUrl: "https://cms.accuweather.com/wp-content/uploads/2023/03/GettyImages-1248014534.jpg?w=64&h=64&crop=1", postedDate: "2023-03-11"}
    ];


    export {articles};